# Generated by Django 4.2.16 on 2024-10-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_bio_profile_image_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
