# Generated by Django 4.2.16 on 2024-10-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='court_jurisdiction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_occurrence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='location_Area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='location_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='parties_involved',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
